### ISSUE TITLE
Getting "coroutine was expected" error while running example

### ISSUE THREAD

**Issue by danaki** [changyuheng/aioserial#13]
Like so:
```
Traceback (most recent call last):
  File "discover.py", line 18, in <module>
    asyncio.run(asyncio.gather(read_and_print(aioserial_instance), aioserial_instance.write_async(b'Hello, World!\n')))
  File "/Users/up/anaconda3/envs/winch/lib/python3.8/asyncio/runners.py", line 37, in run
    raise ValueError("a coroutine was expected, got {!r}".format(main))
ValueError: a coroutine was expected, got <_GatheringFuture pending>
```

Python 3.8

**Comment by eling22** [comment]
you can turn:
`asyncio.run(asyncio.gather(read_and_print(aioserial_instance), aioserial_instance.write_async(b'Hello, World!\n')))`
to
```
async def tasks(aioserial_instance: aioserial.AioSerial):
    await asyncio.gather(read_and_print(aioserial_instance), aioserial_instance.write_async(b'Hello, World!\n'))

asyncio.run(tasks(aioserial_instance))
```

**Comment by Yuirii** [comment]
@eling22 Thanks！
